### ISSUE TITLE
Download Exercise files 

### ISSUE THREAD

**Issue by tendor09** [mrvogiacu/Decrypt-PluralSight-Videos-GUI#29]
Dear dear developer,

Do you think you can incorporated a decrypt Exercises feature from the offline player crypted content? Or the courses exercises files are not downloaded in the offline courses path?

Many thanks.

**Comment by mrvogiacu** [comment]
1. I tried to disable encrypt in POP and it's work. But you still need a tool to rename course folder, module name, and clip name.
2. The clip was encrypted by POP when downloading from the Pluralsight server. And avoid your account was banned. I think you should using POP to download instead of a third-party tool

**Comment by tendor09** [comment]
Many thanks for the in deep explanations! 
I will close the issue.
